/** 日本传统色 — a curated Japanese-traditional-colour palette for the editor. */
export const JP_COLORS: { name: string; hex: string }[] = [
  { name: '桜色', hex: '#FEF4F4' }, { name: '紅梅色', hex: '#F2A0A1' },
  { name: '撫子色', hex: '#EEBBCB' }, { name: '鴇色', hex: '#F4B3C2' },
  { name: '珊瑚色', hex: '#F5B1AA' }, { name: '朱色', hex: '#EB6101' },
  { name: '緋色', hex: '#D3381C' }, { name: '茜色', hex: '#B7282E' },
  { name: '臙脂', hex: '#B94047' }, { name: '蘇芳', hex: '#973C3F' },
  { name: '牡丹色', hex: '#E7609E' }, { name: '山吹色', hex: '#F8B500' },
  { name: '黄丹', hex: '#EE7800' }, { name: '萱草色', hex: '#F8B862' },
  { name: '卵色', hex: '#FCD575' }, { name: '蒲公英色', hex: '#FFD900' },
  { name: '鶯色', hex: '#928C36' }, { name: '萌黄', hex: '#AACF53' },
  { name: '若草色', hex: '#C3D825' }, { name: '抹茶色', hex: '#C5C56A' },
  { name: '常磐色', hex: '#007B43' }, { name: '若竹色', hex: '#68BE8D' },
  { name: '青磁色', hex: '#7EBEAB' }, { name: '翡翠色', hex: '#38B48B' },
  { name: '浅葱色', hex: '#00A3AF' }, { name: '空色', hex: '#A0D8EF' },
  { name: '縹色', hex: '#2792C3' }, { name: '露草色', hex: '#38A1DB' },
  { name: '群青色', hex: '#4C6CB3' }, { name: '瑠璃色', hex: '#1E50A2' },
  { name: '藍色', hex: '#165E83' }, { name: '紺色', hex: '#223A70' },
  { name: '桔梗色', hex: '#5654A2' }, { name: '江戸紫', hex: '#745399' },
  { name: '藤色', hex: '#BBBCDE' }, { name: '菖蒲色', hex: '#674598' },
  { name: '鳶色', hex: '#95483F' }, { name: '煉瓦色', hex: '#B55233' },
  { name: '黄土色', hex: '#C39143' }, { name: '利休鼠', hex: '#888E7E' },
  { name: '鼠色', hex: '#949495' }, { name: '墨', hex: '#1C1C1C' },
  { name: '胡粉色', hex: '#FFFFFB' },
]
