[package]
name = "jrpg-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "jrpg"
path = "src/main.rs"

[dependencies]
jrpg-engine-dsl = { path = "../jrpg-engine-dsl" }
jrpg-runner = { path = "../jrpg-runner" }
jrpg-rules = { path = "../jrpg-rules" }
jrpg-app = { path = "../jrpg-app" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { version = "4", features = ["derive"] }
