[package]
name = "dotzuki-app"
version.workspace = true
edition.workspace = true
description = "A generic desktop app crate wrapping dotzuki-renderer's game loop"
license.workspace = true
repository.workspace = true

[features]
default = ["desktop"]
desktop = ["dotzuki-renderer/gpu", "dep:notify"]

[dependencies]
dotzuki-engine = { path = "../dotzuki-engine", version = "0.7.0" }
dotzuki-renderer = { path = "../dotzuki-renderer", version = "0.7.0", default-features = false }
notify = { version = "6", optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = "0.4"
