[package]
name = "jrpg-engine-dsl"
version.workspace = true
edition.workspace = true

[dependencies]
jrpg-engine-script = { path = "../jrpg-engine-script" }
sourcemap = "9.3.2"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
miette = { workspace = true }

[build-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
sourcemap = "9.3.2"
miette = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
base64 = "0.22"
insta = "1.47.2"
